default: &default
  adapter: postgresql
  encoding: unicode
  database: daniellabatlle_development
  pool: 5

development:
  <<: *default
  database: daniellabatlle_development

test:
  <<: *default
  database: daniellabatlle_test

staging:
  <<: *default
  database: daniellabatlle_staging

production:
  <<: *default
  database: daniellabatlle_production
